---
services:
  nebula-sync:
    image: ${DOCKER_IMAGE_NS_NEBULA_SYNC:-ghcr.io/lovelaze/nebula-sync:latest}
    container_name: ${CONTAINER_NAME_NS_NEBULA_SYNC:-nebula-sync}
    hostname: ${HOST_NAME_NS_NEBULA_SYNC:-nebula-sync}
    restart: ${RESTART_NS_NEBULA_SYNC:-always}
    networks:
      traefiknet:
        ipv4_address: ${IP_NS_NEBULA_SYNC:-172.16.0.4}
    deploy:
      resources:
        limits:
          cpus: ${CPU_MAX_NS_NEBULA_SYNC:-0.5}
          memory: ${RAM_MAX_NS_NEBULA_SYNC:-128M}
        reservations:
          cpus: ${CPU_MIN_NS_NEBULA_SYNC:-0.05}
          memory: ${RAM_MIN_NS_NEBULA_SYNC:-6M}
    environment:
      - PRIMARY=${PRIMARY_PIHOLE_URL}|${PRIMARY_PIHOLE_PASSWORD}
      - REPLICAS=${REPLICA_1_URL}|${REPLICA_1_PASSWORD},${REPLICA_2_URL}|${REPLICA_2_PASSWORD}
      - FULL_SYNC=true
      - RUN_GRAVITY=true
      - CRON=0 * * * *
      - TZ=${TZ}
    env_file:
      - .env
      - ../00.env/host.env
      - ../00.env/network.env

networks:
  traefiknet:
    name: ${DOCKER_NETWORK:-traefiknet}
    external: true
