services:
  gatus:
    image: ${DOCKER_IMAGE_GA_GATUS:-ghcr.io/twin/gatus}:${DOCKER_IMAGE_GA_GATUS_TAG:-v5.35.0}
    container_name: ${CONTAINER_NAME_GA_GATUS:-gatus}
    hostname: ${HOST_NAME_GA_GATUS:-gatus}
    restart: ${RESTART_GA_GATUS:-always}
    networks:
      traefiknet:
        ipv4_address: ${IP_GA_GATUS:-172.16.0.5}
    deploy:
      resources:
        limits:
          cpus: ${CPU_MAX_GA_GATUS:-1.5}
          memory: ${RAM_MAX_GA_GATUS:-512M}
        reservations:
          cpus: ${CPU_MIN_GA_GATUS:-0.05}
          memory: ${RAM_MIN_GA_GATUS:-6M}
    extends:
      file: ports.yml # Change the ports config if you want to expose this container on different interfaces or ports. By default it is set to only be exposed through traefik, but you can change it to be exposed on localhost (all interfaces) or tailscale IP only. If you change it to localhost or tailscale, it will also be exposed through traefik if you have it.
      service: ${GA_GATUS_PORT_CONFIG:-traefik} # traefik = only through traefik, localhost = bind to all interfaces on the host, tailscale = bind to tailscale IP only
    env_file:
      - .env
      - ../00.env/host.env
      - ../00.env/network.env
    volumes:
      - ${DIR_COMPOSE}/${DIR_GA_GATUS}/config:/config
      - ${DIR_DATA}/${DIR_GA_GATUS}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME_GA_GATUS:-gatus}.entrypoints=http"
      - "traefik.http.routers.${APP_NAME_GA_GATUS:-gatus}.rule=Host(`${APP_NAME_GA_GATUS:-gatus}.${HOST_NAME}.${DOMAIN}`)"
      - "traefik.http.middlewares.${APP_NAME_GA_GATUS:-gatus}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${APP_NAME_GA_GATUS:-gatus}.middlewares=${APP_NAME_GA_GATUS:-gatus}-https-redirect"
      - "traefik.http.routers.${APP_NAME_GA_GATUS:-gatus}-secure.entrypoints=https"
      - "traefik.http.routers.${APP_NAME_GA_GATUS:-gatus}-secure.rule=Host(`${APP_NAME_GA_GATUS:-gatus}.${HOST_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME_GA_GATUS:-gatus}-secure.tls=true"
      - "traefik.http.routers.${APP_NAME_GA_GATUS:-gatus}-secure.service=${APP_NAME_GA_GATUS:-gatus}"
      - "traefik.http.services.${APP_NAME_GA_GATUS:-gatus}.loadbalancer.server.port=${PORT_GA_GATUS_INTERNAL:-8080}"
      - "traefik.docker.network=traefiknet"

networks:
  traefiknet:
    name: ${DOCKER_NETWORK:-traefiknet}
    external: true