services:
  all:
  # This makes Traefik available on all network interfaces of the host, including the host IP and through Traefik (if enabled)
    ports:
      - 80:80
      - 443:443
  
  # This makes Traefik available only on the host computer, not to any other computers on the same network
  localhost:
    ports:
      - 80:80
      - 443:443
  
  # This makes Traefik available only on the Tailscale IP address of the host, allowing access over Tailscale VPN and through Traefik (if enabled)
  tailscale:
    ports:
      - ${IP_TAILSCALE}:80:80
      - ${IP_TAILSCALE}:443:443