name: ${STACK_GT_GLUETUN:-gluetun}
services:
  gluetun:
    image: ${DOCKER_IMAGE_GT_GLUETUN:-qmcgaw/gluetun}
    container_name: ${CONTAINER_NAME_GT_GLUETUN:-gluetun}
    hostname: ${HOST_NAME_GT_GLUETUN:-gluetun}
    restart: ${RESTART_GT_GLUETUN:-unless-stopped}
    cap_add:
      - NET_ADMIN # Required for VPN functionality
    networks:
      traefiknet:
        ipv4_address: ${IP_GT_GLUETUN:-172.16.0.18}
    # It is better to let the gluetun container manage resource itself.
    # deploy:
    #   resources:
    #     limits:
    #       cpus: ${CPU_MAX_GT_GLUETUN}
    #       memory: ${RAM_MAX_GT_GLUETUN}
    #     reservations:
    #       cpus: ${CPU_MIN_GT_GLUETUN:-0.05}
    #       memory: ${RAM_MIN_GT_GLUETUN:-6M}
    env_file:
      - .env
      - ../00.env/host.env
      - ../00.env/network.env
      - ../00.env/vpn.env
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      # OPENVPN settings
      # - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.ovpn # not needed if you have provide the below 3 variables
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_ENDPOINT_PORT=${OPENVPN_PORT}
      # WIREGUARD settings # Uncomment the below lines to use wireguard instead of openvpn, and comment out the openvpn settings above.
      # - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      # - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      # - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      # - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      # - WIREGUARD_PORT=${WIREGUARD_PORT}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - SERVER_CITIES=${SERVER_CITIES}
      - TZ=${TZ}
      # Uncomment the below line if you want to access the VPN through the host.
      # - SHADOWSOCKS=on
    extends:
      file: ports.yml # Change the ports config if you want to expose this container on different interfaces or ports. By default it is set to only be exposed through traefik, but you can change it to be exposed on localhost (all interfaces) or tailscale IP only. If you change it to localhost or tailscale, it will also be exposed through traefik if enabled.
      service: ${GT_GLUETUN_PORT_CONFIG:-traefik} # traefik = only through traefik, all = bind to all interfaces on the host & traefik (if enabled), localhost = bind to only localhost, only host machine can access the port and no other devices on the same network and traefik (if enabled), tailscale = bind to tailscale IP only & traefik (if enabled)
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${DIR_HOMESTACK}/data/${DIR_GLUETUN:-gluetun}:/gluetun
    # You do not need to change the external port, it is designed to work nicely with other containers.
    ports:
      - ${IP_TAILSCALE}:4000:8000/tcp # gluetun web API
      - ${IP_TAILSCALE}:4001:8888/tcp # HTTP intranet
      - ${IP_TAILSCALE}:4002:8388/tcp # Shadowsocks
      - ${IP_TAILSCALE}:4002:8388/udp # Shadowsocks
      # - ${IP_TAILSCALE}:4004:8080 # qbittorrent
      - ${IP_TAILSCALE}:4005:6881/tcp # qbittorrent
      - ${IP_TAILSCALE}:4005:6881/udp # qbittorrent
      # - 4006:5055 # oversearr
      # - 4007:8989/tcp # sonarr
      # - 4008:7878/tcp # radarr
      # - 4009:8686/tcp # lidarr
      # - 4010:8787/tcp # readarr
      # - 4011:6767 # bazarr
      # - 4012:9696 # prowlarr
      # - 4013:80 # speedtest
      # - 4014:3000 # firefox
      # - 4015:8081 # metube
      # - 4016:8191 # flaresolverr
      # - 4545:4545 # requestrr
      - ${IP_TAILSCALE}:6881:6881 # deluge
      - ${IP_TAILSCALE}:6881:6881/udp # deluge
      - ${IP_TAILSCALE}:58846:58846 # deluge
      # OR if you don't want to bind to a specific IP, you can use:
      # 4000:8000/tcp # gluetun web API
      # 4001:8888/tcp # HTTP intranet
      # 4002:8388/tcp # Shadowsocks
      # 4002:8388/udp # Shadowsocks
      # 4004:8080 # qbittorrent
      # 4005:6881/tcp # qbittorrent
      # 4005:6881/udp # qbittorrent
      # 4006:5055 # oversearr
      # 4007:8989/tcp # sonarr
      # 4008:7878/tcp # radarr
      # 4009:8686/tcp # lidarr
      # 4010:8787/tcp # readarr
      # 4011:6767 # bazarr
      # 4012:9696 # prowlarr
      # 4013:80 # speedtest
      # 4014:3000 # firefox
      # 4015:8081 # metube
      # 4016:8191 # flaresolverr
      # 4545:4545 # requestrr
      # - 6881:6881 # deluge
      # - 6881:6881/udp # deluge
      # - 58846:58846 # deluge


networks:
  traefiknet:
    name: ${DOCKER_NETWORK:-traefiknet}
    external: true
