name: ${STACK_FB_FILEBROWSER:-filebrowser}
services:
  filebrowser:
    image: ${DOCKER_IMAGE_FB_FILEBROWSER:-filebrowser/filebrowser:s6}
    container_name: ${CONTAINER_NAME_FB_FILEBROWSER:-filebrowser}
    # user: ${UID}:${GID}
    hostname: ${HOST_NAME_FB_FILEBROWSER:-filebrowser}
    restart: ${RESTART_POLICY_FB_FILEBROWSER:-unless-stopped}
    deploy:
      resources:
        limits:
          cpus: ${CPU_MAX_FB_FILEBROWSER}
          memory: ${RAM_MAX_FB_FILEBROWSER}
        reservations:
          cpus: ${CPU_MIN_FB_FILEBROWSER:-0.05}
          memory: ${RAM_MIN_FB_FILEBROWSER:-6M}
    networks:
      traefiknet:
        ipv4_address: ${IP_FB_FILEBROWSER:-172.16.0.12}
    env_file:
      - .env
      - ../00.env/host.env
      - ../00.env/network.env
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    # Uncomment this if not running traefik or other reverse proxy and want to access gatus directly via http://<IP_PUBLIC>:3006 or http://<IP_TAILSCALE>:3006
    # You do not need to change the external port, it is designed to work nicely with other containers.
    # ports:
    #   - ${IP_TAILSCALE}:${PORT_FB_FILEBROWSER_EXTERNAL:-3006}:${PORT_FB_FILEBROWSER_INTERNAL:-80}/tcp
    # OR if you don't want to bind to a specific IP, you can use:
    # ${PORT_FB_FILEBROWSER_EXTERNAL:-3006}:${PORT_FB_FILEBROWSER_INTERNAL:-80}/tcp
    volumes:
      - ${DIR_DATA}/${DIR_FB_FILEBROWSER}/config:/config
      - ${DIR_DATA}/${DIR_FB_FILEBROWSER}/database:/database
      - ${DIR_DATA}/${DIR_FB_FILEBROWSER}/src:/srv
      # Add any mounts here, for example:
      # - ${DIR_HOME}:/home
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME_FB_FILEBROWSER:-filebrowser}.entrypoints=http"
      - "traefik.http.routers.${APP_NAME_FB_FILEBROWSER:-filebrowser}.rule=Host(`${APP_NAME_FB_FILEBROWSER:-filebrowser}.${HOST_NAME}.${DOMAIN}`)"
      - "traefik.http.middlewares.${APP_NAME_FB_FILEBROWSER:-filebrowser}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${APP_NAME_FB_FILEBROWSER:-filebrowser}.middlewares=${APP_NAME_FB_FILEBROWSER:-filebrowser}-https-redirect"
      - "traefik.http.routers.${APP_NAME_FB_FILEBROWSER:-filebrowser}-secure.entrypoints=https"
      - "traefik.http.routers.${APP_NAME_FB_FILEBROWSER:-filebrowser}-secure.rule=Host(`${APP_NAME_FB_FILEBROWSER:-filebrowser}.${HOST_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME_FB_FILEBROWSER:-filebrowser}-secure.tls=true"
      - "traefik.http.routers.${APP_NAME_FB_FILEBROWSER:-filebrowser}-secure.service=${APP_NAME_FB_FILEBROWSER:-filebrowser}"
      - "traefik.http.services.${APP_NAME_FB_FILEBROWSER:-filebrowser}.loadbalancer.server.port=${PORT_FB_FILEBROWSER_INTERNAL:-80}"
      - "traefik.docker.network=traefiknet"

networks:
  traefiknet:
    name: ${DOCKER_NETWORK:-traefiknet}
    external: true