name: ${STACK_VW_VAULTWARDEN:-vault}
services:
  vault:
    image: ${DOCKER_IMAGE_VW_VAULTWARDEN:-vaultwarden/server:latest}
    container_name: ${CONTAINER_NAME_VW_VAULTWARDEN:-vault}
    hostname: ${HOST_NAME_VW_VAULTWARDEN:-vault}
    restart: ${RESTART_VW_VAULTWARDEN:-unless-stopped}
    # user: "${UID}:${GID}"
    networks:
      traefiknet:
        ipv4_address: ${IP_VW_VAULTWARDEN:-172.16.0.16}
    deploy:
      resources:
        limits:
          cpus: ${CPU_MAX_VW_VAULTWARDEN}
          memory: ${RAM_MAX_VW_VAULTWARDEN}
        reservations:
          cpus: ${CPU_MIN_VW_VAULTWARDEN:-0.05}
          memory: ${RAM_MIN_VW_VAULTWARDEN:-6M}
    env_file:
      - .env
      - ../00.env/host.env
      - ../00.env/network.env
      - ../00.env/email.env
    environment:
      #- ROCKET_PORT=80
      #- ROCKET_WORKERS=10
      - WEB_VAULT_URL=https://${APP_NAME_VW_VAULTWARDEN:-vault}.${HOST_NAME}.${DOMAIN}
      - DOMAIN=https://${APP_NAME_VW_VAULTWARDEN:-vault}.${HOST_NAME}.${DOMAIN}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
      - INVITATIONS_ALLOWED=${INVITATIONS_ALLOWED}
      - PASSWORD_ITERATIONS=800000
      #- SIGNUPS_DOMAINS_WHITELIST=example.com,example.net,example.org
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN} # Create one using `echo -n 'MySecretPassword' | argon2 "$(openssl rand -base64 32)" -e -id -k 65540 -t 3 -p 4` and make sure it is in single quotes eg. '$argon2id$v=19$m=65540,t=3,p=4$MmeK.....'
      - ENABLE_DB_WAL=true
      - SMTP_HOST=${SMTP_SERVER}
      - SMTP_FROM=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_SECURITY=${SMTP_SECURITY}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_EMBED_IMAGES=yes
    # Uncomment this if not running traefik or other reverse proxy and want to access gatus directly via http://<IP_PUBLIC>:3010 or http://<IP_TAILSCALE>:3010
    # You do not need to change the external port, it is designed to work nicely with other containers.
    # ports:
    #   - ${IP_TAILSCALE}:${PORT_VW_VAULTWARDEN_EXTERNAL:-3010}:${PORT_VW_VAULTWARDEN_INTERNAL:-80}
    # OR if you don't want to bind to a specific IP, you can use:
    # ${PORT_VW_VAULTWARDEN_EXTERNAL:-3010}:${PORT_VW_VAULTWARDEN_INTERNAL:-80}
    volumes:
      - ${DIR_DATA}/${DIR_VW_VAULTWARDEN:-vaultwarden}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME_VW_VAULTWARDEN:-vault}.entrypoints=http"
      - "traefik.http.routers.${APP_NAME_VW_VAULTWARDEN:-vault}.rule=Host(`${APP_NAME_VW_VAULTWARDEN:-vault}.${HOST_NAME}.${DOMAIN}`)"
      - "traefik.http.middlewares.${APP_NAME_VW_VAULTWARDEN:-vault}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${APP_NAME_VW_VAULTWARDEN:-vault}.middlewares=${APP_NAME_VW_VAULTWARDEN:-vault}-https-redirect"
      - "traefik.http.routers.${APP_NAME_VW_VAULTWARDEN:-vault}-secure.entrypoints=https"
      - "traefik.http.routers.${APP_NAME_VW_VAULTWARDEN:-vault}-secure.rule=Host(`${APP_NAME_VW_VAULTWARDEN:-vault}.${HOST_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME_VW_VAULTWARDEN:-vault}-secure.tls=true"
      - "traefik.http.routers.${APP_NAME_VW_VAULTWARDEN:-vault}-secure.service=${APP_NAME_VW_VAULTWARDEN:-vault}"
      - "traefik.http.services.${APP_NAME_VW_VAULTWARDEN:-vault}.loadbalancer.server.port=${PORT_VW_VAULTWARDEN_INTERNAL:-80}"
      - "traefik.docker.network=traefiknet"

networks:
  traefiknet:
    name: ${DOCKER_NETWORK:-traefiknet}
    external: true
