"""Integration tests for pull → deploy workflow."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock

import pytest
from cli import cli as cli_module
from models.projects import ProjectItem
from parsers import EnvTemplateParser
from typer.testing import CliRunner
from utils.docker_runtime import ContainerStatus, DeploymentResult, DockerRuntimeError
from utils.shared_pref import HostPreferences


def _project_item(**overrides: object) -> ProjectItem:
    payload: dict[str, object] = {
        "project_index": 1,
        "project_name": "Test Project",
        "dir_name": "99.test-project",
        "compose": "docker-compose.yml",
        "env": ".env.template",
        "readme": "readme.md",
        "required_env_files": ["host.env", "network.env"],
    }
    payload.update(overrides)
    return ProjectItem(**payload)


@pytest.fixture
def sample_project() -> dict:
    """Sample project for pull/deploy tests."""
    return {
        "project_index": 1,
        "project_name": "Test Project",
        "dir_name": "99.test-project",
        "compose": "docker-compose.yml",
        "env": ".env.template",
        "readme": "readme.md",
    }


@pytest.fixture
def sample_env_template() -> str:
    """Sample .env.template file."""
    return """# Test Service Configuration
# This template defines environment variables for the test service.

## Basic Configuration
TEST_HOSTNAME=myhost
TEST_PORT=8080

## Secrets (generated automatically)
# SECURE_KEY: An autogenerated secret key for encryption
SECURE_KEY={}

# PASSWORD: A secure password (recommended: xkcdpass)
PASSWORD={}

## Optional Settings
DEBUG=false
LOG_LEVEL=info
"""


@pytest.fixture
def sample_compose_file() -> str:
    """Sample docker-compose.yml file."""
    return """version: '3.8'

services:
  test-service:
    image: test-service:latest
    container_name: test-service
    environment:
      - HOSTNAME=${TEST_HOSTNAME}
      - PORT=${TEST_PORT}
      - SECURE_KEY=${SECURE_KEY}
      - PASSWORD=${PASSWORD}
    ports:
      - "${TEST_PORT}:${TEST_PORT}"
    restart: unless-stopped
"""


def test_pull_downloads_project_files(
    tmp_path: Path,
    sample_project: dict,
    sample_env_template: str,
    sample_compose_file: str,
):
    """Test that pull downloads docker-compose.yml and .env.template."""
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "Test Project"
    project_dir.mkdir(parents=True, exist_ok=True)

    # Simulate download by writing files
    (project_dir / ".env.template").write_text(sample_env_template, encoding="utf-8")
    (project_dir / "docker-compose.yml").write_text(
        sample_compose_file, encoding="utf-8"
    )

    # Verify files exist
    assert (project_dir / ".env.template").exists()
    assert (project_dir / "docker-compose.yml").exists()

    # Verify content
    template_content = (project_dir / ".env.template").read_text(encoding="utf-8")
    assert "TEST_HOSTNAME" in template_content
    assert "SECURE_KEY" in template_content


def test_parse_env_template(tmp_path: Path, sample_env_template: str):
    """Test that .env.template is parsed correctly."""
    template_path = tmp_path / ".env.template"
    template_path.write_text(sample_env_template, encoding="utf-8")

    parser = EnvTemplateParser(template_path)
    parsed = parser.parse()

    assert parsed is not None
    # Verify template was parsed
    assert len(parsed.variables) > 0 or parsed.metadata is not None


def test_deploy_preparation_generates_env(
    tmp_path: Path,
    sample_env_template: str,
    sample_compose_file: str,
):
    """Test that deploy generates .env file from template."""
    project_dir = tmp_path / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    # Write template and compose files
    template_path = project_dir / ".env.template"
    compose_path = project_dir / "docker-compose.yml"
    template_path.write_text(sample_env_template, encoding="utf-8")
    compose_path.write_text(sample_compose_file, encoding="utf-8")

    # Verify files exist
    assert template_path.exists()
    assert compose_path.exists()

    # Simulate env generation (in real deploy, this uses questionary + build_form_from_template)
    env_content = """TEST_HOSTNAME=example.local
TEST_PORT=8080
SECURE_KEY=abc123xyzabc123xyzabc123xyz
PASSWORD=correct-horse-battery-staple
DEBUG=false
LOG_LEVEL=info
"""
    env_path = project_dir / ".env"
    env_path.write_text(env_content, encoding="utf-8")

    # Verify .env was created
    assert env_path.exists()
    env_text = env_path.read_text(encoding="utf-8")
    assert "TEST_HOSTNAME=example.local" in env_text
    assert "SECURE_KEY=" in env_text


def test_docker_runtime_loads_compose_subset(tmp_path: Path, sample_compose_file: str):
    """Test that the Docker runtime input files are prepared correctly."""
    project_dir = tmp_path / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    compose_file = (project_dir / "docker-compose.yml").resolve()
    generated_env_file = (project_dir / ".env").resolve()
    host_env_file = (tmp_path / "00.env" / "host.env").resolve()
    network_env_file = (tmp_path / "00.env" / "network.env").resolve()

    compose_file.write_text(sample_compose_file, encoding="utf-8")
    generated_env_file.write_text("TEST_HOSTNAME=localhost\nTEST_PORT=8080\n")
    host_env_file.parent.mkdir(parents=True, exist_ok=True)
    host_env_file.write_text("HOST_UID=1000\nHOST_GID=1000\n", encoding="utf-8")
    network_env_file.write_text("TZ=UTC\n", encoding="utf-8")

    assert compose_file.exists()
    assert generated_env_file.exists()
    assert host_env_file.exists()
    assert network_env_file.exists()


def test_docker_runtime_failure_handling(tmp_path: Path):
    """Test that a Docker runtime failure surfaces as an error message."""
    project_dir = tmp_path / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)
    compose_file = (project_dir / "docker-compose.yml").resolve()
    generated_env_file = (project_dir / ".env").resolve()
    host_env_file = (tmp_path / "00.env" / "host.env").resolve()
    network_env_file = (tmp_path / "00.env" / "network.env").resolve()

    compose_file.write_text("services: {}\n", encoding="utf-8")
    generated_env_file.write_text("TEST_HOSTNAME=localhost\n", encoding="utf-8")
    host_env_file.parent.mkdir(parents=True, exist_ok=True)
    host_env_file.write_text("HOST_UID=1000\n", encoding="utf-8")
    network_env_file.write_text("TZ=UTC\n", encoding="utf-8")

    assert compose_file.exists()
    assert generated_env_file.exists()
    assert host_env_file.exists()
    assert network_env_file.exists()


def test_docker_runtime_status_payload_shape(tmp_path: Path):
    """Test that the runtime status payload fields are represented."""
    project_dir = tmp_path / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    status = ContainerStatus(
        service_name="test-service",
        container_name="test-service",
        status="running",
        image="test-service:latest",
    )
    assert status.service_name == "test-service"
    assert status.status == "running"


@pytest.mark.integration
def test_full_pull_deploy_workflow(
    tmp_path: Path,
    sample_project: dict,
    sample_env_template: str,
    sample_compose_file: str,
):
    """Integration test: pull → parse template → generate env → docker compose."""
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"

    # Step 1: Pull project files
    project_dir = compose_dir / sample_project["project_name"]
    project_dir.mkdir(parents=True, exist_ok=True)

    template_path = project_dir / ".env.template"
    compose_path = project_dir / "docker-compose.yml"
    template_path.write_text(sample_env_template, encoding="utf-8")
    compose_path.write_text(sample_compose_file, encoding="utf-8")

    assert template_path.exists()
    assert compose_path.exists()

    # Step 2: Parse template
    parser = EnvTemplateParser(template_path)
    parsed = parser.parse()
    assert parsed is not None

    # Step 3: Generate .env (simulated)
    env_content = """TEST_HOSTNAME=localhost
TEST_PORT=8080
SECURE_KEY=test-secret-abc123
PASSWORD=test-password-xyz789
DEBUG=false
LOG_LEVEL=info
"""
    env_path = project_dir / ".env"
    env_path.write_text(env_content, encoding="utf-8")
    assert env_path.exists()

    host_env_path = (compose_dir / "00.env" / "host.env").resolve()
    network_env_path = (compose_dir / "00.env" / "network.env").resolve()
    host_env_path.parent.mkdir(parents=True, exist_ok=True)
    host_env_path.write_text("HOST_UID=1000\nHOST_GID=1000\n", encoding="utf-8")
    network_env_path.write_text("TZ=UTC\n", encoding="utf-8")

    # Step 4: Verify Docker runtime inputs are prepared.
    compose_file = compose_path.resolve()
    generated_env_file = env_path.resolve()
    assert compose_file.exists()
    assert generated_env_file.exists()
    assert host_env_path.exists()
    assert network_env_path.exists()

    # Step 5: Verify final state
    assert (project_dir / ".env").exists()
    assert (project_dir / "docker-compose.yml").exists()
    assert (project_dir / ".env.template").exists()


def test_deploy_fails_when_host_env_missing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_query = "test"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "docker-compose.yml").write_text("services: {}\n", encoding="utf-8")
    (project_dir / ".env.template").write_text(
        "TEST_VAR=example # recommended=example\n", encoding="utf-8"
    )

    # Ensure host.env is missing and network.env exists.
    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    (env_dir / "network.env").write_text("TZ=UTC\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [_project_item()],
    )

    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "deploy_project_stack", runtime_mock)
    result = runner.invoke(
        cli_module.app,
        ["deploy", project_query, "--use-recommended"],
    )

    assert result.exit_code == 1
    expected = f"Required env file not found: {(env_dir / 'host.env').resolve()}"
    assert expected in result.output
    runtime_mock.assert_not_called()


def test_deploy_fails_when_network_env_missing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_query = "test"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "docker-compose.yml").write_text("services: {}\n", encoding="utf-8")
    (project_dir / ".env.template").write_text(
        "TEST_VAR=example # recommended=example\n", encoding="utf-8"
    )

    # Ensure host.env exists and network.env is missing.
    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    (env_dir / "host.env").write_text("HOST_UID=1000\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [_project_item()],
    )

    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "deploy_project_stack", runtime_mock)
    result = runner.invoke(
        cli_module.app,
        ["deploy", project_query, "--use-recommended"],
    )

    assert result.exit_code == 1
    expected = f"Required env file not found: {(env_dir / 'network.env').resolve()}"
    assert expected in result.output
    runtime_mock.assert_not_called()


def test_deploy_lists_matching_projects(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "docker-compose.yml").write_text("services: {}\n", encoding="utf-8")
    (project_dir / ".env.template").write_text(
        "TEST_VAR=example # recommended=example\n", encoding="utf-8"
    )

    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    (env_dir / "host.env").write_text("HOST_UID=1000\n", encoding="utf-8")
    (env_dir / "network.env").write_text("TZ=UTC\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [_project_item()],
    )

    deployment = DeploymentResult(
        containers=[
            ContainerStatus(
                service_name="test-service",
                container_name="test-service",
                status="running",
                image="test-service:latest",
            )
        ]
    )
    runtime_mock = MagicMock(return_value=deployment)
    monkeypatch.setattr(cli_module, "validate_compose_config", MagicMock())
    monkeypatch.setattr(cli_module, "deploy_project_stack", runtime_mock)
    result = runner.invoke(
        cli_module.app,
        ["deploy", "test", "--use-recommended"],
    )

    assert result.exit_code == 0
    assert "Test Project" in result.output
    assert "Docker deployment completed successfully." in result.output


def test_deploy_pulls_when_project_missing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    selected_project_name = "Test Project"
    selected_slug = "test-project"

    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    (env_dir / "host.env").write_text("HOST_UID=1000\n", encoding="utf-8")
    (env_dir / "network.env").write_text("TZ=UTC\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [
            _project_item(project_name=selected_project_name)
        ],
    )

    pull_calls: list[tuple[str, Path, bool]] = []

    def fake_pull_project_files(
        selected: ProjectItem, compose_dir_arg: Path, *, force: bool = False
    ) -> tuple[Path, int, list[Path]]:
        pull_calls.append((selected.project_name, compose_dir_arg, force))
        project_dir = compose_dir_arg / selected_slug
        project_dir.mkdir(parents=True, exist_ok=True)
        (project_dir / "docker-compose.yml").write_text(
            "services: {}\n", encoding="utf-8"
        )
        (project_dir / ".env.template").write_text(
            "TEST_VAR=example # recommended=example\n", encoding="utf-8"
        )
        (project_dir / "readme.md").write_text("# Readme\n", encoding="utf-8")
        return project_dir, 3, []

    monkeypatch.setattr(cli_module, "_pull_project_files", fake_pull_project_files)

    runtime_mock = MagicMock(return_value=DeploymentResult(containers=[]))
    monkeypatch.setattr(cli_module, "validate_compose_config", MagicMock())
    monkeypatch.setattr(cli_module, "deploy_project_stack", runtime_mock)
    result = runner.invoke(
        cli_module.app,
        ["deploy", "test", "--use-recommended"],
    )

    assert result.exit_code == 0
    assert "pulling project files first" in result.output.lower()
    assert len(pull_calls) == 1
    assert pull_calls[0][0] == selected_project_name
    assert pull_calls[0][1] == compose_dir.resolve()
    assert pull_calls[0][2] is False


def test_pull_refuses_to_overwrite_existing_files_without_force(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "docker-compose.yml").write_text("services: {}\n", encoding="utf-8")
    (project_dir / ".env.template").write_text("TEST=1\n", encoding="utf-8")
    (project_dir / "readme.md").write_text("# test\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir: [_project_item()],
    )

    result = runner.invoke(cli_module.app, ["pull", "test"])

    assert result.exit_code == 1
    assert "already exist" in result.output.lower()
    assert "--force" in result.output


def test_pull_downloads_config_files(monkeypatch: pytest.MonkeyPatch, tmp_path: Path):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir: [
            _project_item(
                config_files=[
                    {"path": "data/acme.json", "constant": True},
                    {
                        "path": "data/config.yml",
                        "constant": False,
                        "keys": {"hello": "world"},
                    },
                ]
            )
        ],
    )

    async def fake_download_jobs(jobs, *, on_job_complete=None):
        for job in jobs:
            job.destination.parent.mkdir(parents=True, exist_ok=True)
            job.destination.write_text(f"downloaded:{job.url}\n", encoding="utf-8")
            if on_job_complete is not None:
                on_job_complete()

    monkeypatch.setattr(cli_module, "_download_jobs", fake_download_jobs)

    result = runner.invoke(cli_module.app, ["pull", "test"])

    assert result.exit_code == 0
    project_dir = compose_dir / "test-project"
    assert (project_dir / "docker-compose.yml").exists()
    assert (project_dir / ".env.template").exists()
    assert (project_dir / "readme.md").exists()
    assert (project_dir / "data" / "acme.json").exists()
    assert (project_dir / "data" / "config.yml").exists()


def test_pull_skips_existing_config_files_without_force(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    existing_config = project_dir / "data" / "acme.json"
    existing_config.parent.mkdir(parents=True, exist_ok=True)
    existing_config.write_text("existing\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir: [
            _project_item(config_files=[{"path": "data/acme.json", "constant": True}])
        ],
    )

    async def fake_download_jobs(jobs, *, on_job_complete=None):
        for job in jobs:
            job.destination.parent.mkdir(parents=True, exist_ok=True)
            job.destination.write_text("new\n", encoding="utf-8")
            if on_job_complete is not None:
                on_job_complete()

    monkeypatch.setattr(cli_module, "_download_jobs", fake_download_jobs)

    result = runner.invoke(cli_module.app, ["pull", "test"])

    assert result.exit_code == 0
    assert "Skipped 1 existing file(s)" in result.output
    assert existing_config.read_text(encoding="utf-8") == "existing\n"


def test_pull_force_overwrites_existing_config_files(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    existing_config = project_dir / "data" / "acme.json"
    existing_config.parent.mkdir(parents=True, exist_ok=True)
    existing_config.write_text("existing\n", encoding="utf-8")

    for name in ["docker-compose.yml", ".env.template", "readme.md"]:
        (project_dir / name).write_text("old\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir: [
            _project_item(
                config_files=[
                    {
                        "path": "data/acme.json",
                        "constant": True,
                        "keys": {"unused": "value"},
                    }
                ]
            )
        ],
    )

    async def fake_download_jobs(jobs, *, on_job_complete=None):
        for job in jobs:
            job.destination.parent.mkdir(parents=True, exist_ok=True)
            job.destination.write_text("new\n", encoding="utf-8")
            if on_job_complete is not None:
                on_job_complete()

    monkeypatch.setattr(cli_module, "_download_jobs", fake_download_jobs)

    result = runner.invoke(cli_module.app, ["pull", "test", "--force"])

    assert result.exit_code == 0
    assert existing_config.read_text(encoding="utf-8") == "new\n"


def test_pull_rejects_unsafe_config_path(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir: [
            _project_item(config_files=[{"path": "../escape.txt", "constant": False}])
        ],
    )

    async def fake_download_jobs(jobs, *, on_job_complete=None):
        pytest.fail("download jobs should not run for invalid config path")

    monkeypatch.setattr(cli_module, "_download_jobs", fake_download_jobs)

    result = runner.invoke(cli_module.app, ["pull", "test"])

    assert result.exit_code == 1
    assert "escapes project directory" in result.output


def test_resolve_project_config_destination_validates_paths(tmp_path: Path):
    project_dir = tmp_path / "compose" / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    safe_destination = cli_module._resolve_project_config_destination(
        project_dir, "data/config.yml"
    )
    assert safe_destination == (project_dir / "data" / "config.yml").resolve()

    with pytest.raises(ValueError, match="escapes project directory"):
        cli_module._resolve_project_config_destination(project_dir, "../escape.yml")


def test_deploy_uses_start_equivalent_flow_when_env_exists(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "docker-compose.yml").write_text("services: {}\n", encoding="utf-8")
    (project_dir / ".env.template").write_text(
        "TEST_VAR=example # recommended=example\n", encoding="utf-8"
    )
    existing_env = project_dir / ".env"
    existing_env.write_text("EXISTING=1\n", encoding="utf-8")

    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    (env_dir / "host.env").write_text("HOST_UID=1000\n", encoding="utf-8")
    (env_dir / "network.env").write_text("TZ=UTC\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [_project_item()],
    )
    monkeypatch.setattr(
        cli_module,
        "EnvTemplateParser",
        lambda *_args, **_kwargs: pytest.fail(
            "deploy should exit before parsing the template when .env already exists"
        ),
    )
    monkeypatch.setattr(
        cli_module,
        "build_form_from_template",
        lambda *_args, **_kwargs: pytest.fail(
            "deploy should exit before prompting when .env already exists"
        ),
    )

    start_runtime_mock = MagicMock()
    deploy_runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "validate_compose_config", MagicMock())
    monkeypatch.setattr(cli_module, "start_project_stack", start_runtime_mock)
    monkeypatch.setattr(cli_module, "deploy_project_stack", deploy_runtime_mock)
    result = runner.invoke(
        cli_module.app,
        ["deploy", "test", "--use-recommended"],
    )

    assert result.exit_code == 0
    assert "Docker deployment completed successfully." in result.output
    assert existing_env.read_text(encoding="utf-8") == "EXISTING=1\n"
    start_runtime_mock.assert_called_once_with(
        (project_dir / "docker-compose.yml").resolve(),
        "test-project",
        [
            existing_env.resolve(),
            (env_dir / "host.env").resolve(),
            (env_dir / "network.env").resolve(),
        ],
    )
    deploy_runtime_mock.assert_not_called()


def test_deploy_fails_when_compose_config_is_invalid(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "docker-compose.yml").write_text("services: {}\n", encoding="utf-8")
    (project_dir / ".env.template").write_text(
        "TEST_VAR=example # recommended=example\n", encoding="utf-8"
    )

    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    custom_env_path = (env_dir / "custom.env").resolve()
    custom_env_path.write_text("CUSTOM_VAR=1\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [
            _project_item(required_env_files=["custom.env"])
        ],
    )

    validation_mock = MagicMock(
        side_effect=DockerRuntimeError("services.test-service.ports is invalid")
    )
    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "validate_compose_config", validation_mock)
    monkeypatch.setattr(cli_module, "deploy_project_stack", runtime_mock)
    result = runner.invoke(
        cli_module.app,
        ["deploy", "test", "--use-recommended"],
    )

    assert result.exit_code == 1
    assert "Docker deploy failed." in result.output
    assert "services.test-service.ports is invalid" in result.output
    validation_mock.assert_called_once_with(
        (project_dir / "docker-compose.yml").resolve(),
        "test-project",
        [(project_dir / ".env").resolve(), custom_env_path],
    )
    runtime_mock.assert_not_called()


def test_stop_runs_docker_runtime(monkeypatch: pytest.MonkeyPatch, tmp_path: Path):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    compose_path = (project_dir / "docker-compose.yml").resolve()
    env_path = (project_dir / ".env").resolve()
    compose_path.write_text("services: {}\n", encoding="utf-8")
    env_path.write_text("TEST_VAR=example\n", encoding="utf-8")

    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    host_env_path = (env_dir / "host.env").resolve()
    network_env_path = (env_dir / "network.env").resolve()
    host_env_path.write_text("HOST_UID=1000\n", encoding="utf-8")
    network_env_path.write_text("TZ=UTC\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [_project_item()],
    )

    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "validate_compose_config", MagicMock())
    monkeypatch.setattr(cli_module, "stop_project_stack", runtime_mock)
    result = runner.invoke(cli_module.app, ["stop", "test"])

    assert result.exit_code == 0
    assert "Docker stop completed successfully." in result.output
    runtime_mock.assert_called_once_with(
        compose_path,
        "test-project",
        [env_path, host_env_path, network_env_path],
    )


def test_stop_lists_matching_installed_projects(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "docker-compose.yml").write_text("services: {}\n", encoding="utf-8")
    (project_dir / ".env").write_text("TEST_VAR=example\n", encoding="utf-8")

    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    (env_dir / "host.env").write_text("HOST_UID=1000\n", encoding="utf-8")
    (env_dir / "network.env").write_text("TZ=UTC\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [_project_item()],
    )

    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "validate_compose_config", MagicMock())
    monkeypatch.setattr(cli_module, "stop_project_stack", runtime_mock)
    result = runner.invoke(cli_module.app, ["stop", "test"])

    assert result.exit_code == 0
    assert "Test Project" in result.output


def test_stop_uses_project_required_env_files(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    compose_path = (project_dir / "docker-compose.yml").resolve()
    env_path = (project_dir / ".env").resolve()
    compose_path.write_text("services: {}\n", encoding="utf-8")
    env_path.write_text("TEST_VAR=example\n", encoding="utf-8")

    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    custom_env_path = (env_dir / "custom.env").resolve()
    custom_env_path.write_text("CUSTOM_VAR=1\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [
            _project_item(required_env_files=["custom.env"])
        ],
    )

    validation_mock = MagicMock()
    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "validate_compose_config", validation_mock)
    monkeypatch.setattr(cli_module, "stop_project_stack", runtime_mock)
    result = runner.invoke(cli_module.app, ["stop", "test"])

    assert result.exit_code == 0
    validation_mock.assert_called_once_with(
        compose_path,
        "test-project",
        [env_path, custom_env_path],
    )
    runtime_mock.assert_called_once_with(
        compose_path,
        "test-project",
        [env_path, custom_env_path],
    )


def test_stop_fails_when_no_installed_projects(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    install_dir.mkdir(parents=True, exist_ok=True)

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [_project_item()],
    )

    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "stop_project_stack", runtime_mock)
    result = runner.invoke(cli_module.app, ["stop", "test"])

    assert result.exit_code == 1
    assert "No locally installed projects were found" in result.output
    runtime_mock.assert_not_called()


def test_start_runs_docker_runtime(monkeypatch: pytest.MonkeyPatch, tmp_path: Path):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    compose_path = (project_dir / "docker-compose.yml").resolve()
    env_path = (project_dir / ".env").resolve()
    compose_path.write_text("services: {}\n", encoding="utf-8")
    env_path.write_text("TEST_VAR=example\n", encoding="utf-8")

    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    host_env_path = (env_dir / "host.env").resolve()
    network_env_path = (env_dir / "network.env").resolve()
    host_env_path.write_text("HOST_UID=1000\n", encoding="utf-8")
    network_env_path.write_text("TZ=UTC\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [_project_item()],
    )

    validation_mock = MagicMock()
    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "validate_compose_config", validation_mock)
    monkeypatch.setattr(cli_module, "start_project_stack", runtime_mock)
    result = runner.invoke(cli_module.app, ["start", "test"])

    assert result.exit_code == 0
    assert "Docker start completed successfully." in result.output
    validation_mock.assert_called_once_with(
        compose_path,
        "test-project",
        [env_path, host_env_path, network_env_path],
    )
    runtime_mock.assert_called_once_with(
        compose_path,
        "test-project",
        [env_path, host_env_path, network_env_path],
    )


def test_deploy_fails_when_required_env_files_metadata_is_missing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "docker-compose.yml").write_text("services: {}\n", encoding="utf-8")
    (project_dir / ".env.template").write_text(
        "TEST_VAR=example # recommended=example\n", encoding="utf-8"
    )

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [
            _project_item(required_env_files=None)
        ],
    )

    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "deploy_project_stack", runtime_mock)
    result = runner.invoke(
        cli_module.app,
        ["deploy", "test", "--use-recommended"],
    )

    assert result.exit_code == 1
    assert "does not define required_env_files" in result.output
    assert "00.api/v1/projects.json" in result.output
    runtime_mock.assert_not_called()


def test_start_fails_when_required_env_files_metadata_is_missing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "docker-compose.yml").write_text("services: {}\n", encoding="utf-8")
    (project_dir / ".env").write_text("TEST_VAR=example\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [
            _project_item(required_env_files=None)
        ],
    )

    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "start_project_stack", runtime_mock)
    result = runner.invoke(cli_module.app, ["start", "test"])

    assert result.exit_code == 1
    assert "does not define required_env_files" in result.output
    assert "00.api/v1/projects.json" in result.output
    runtime_mock.assert_not_called()


def test_remove_runs_runtime_and_deletes_project_dir(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
):
    runner = CliRunner()
    install_dir = tmp_path / "homestack"
    compose_dir = install_dir / "compose"
    project_dir = compose_dir / "test-project"
    project_dir.mkdir(parents=True, exist_ok=True)

    compose_path = (project_dir / "docker-compose.yml").resolve()
    env_path = (project_dir / ".env").resolve()
    compose_path.write_text("services: {}\n", encoding="utf-8")
    env_path.write_text("TEST_VAR=example\n", encoding="utf-8")

    env_dir = compose_dir / "00.env"
    env_dir.mkdir(parents=True, exist_ok=True)
    host_env_path = (env_dir / "host.env").resolve()
    network_env_path = (env_dir / "network.env").resolve()
    host_env_path.write_text("HOST_UID=1000\n", encoding="utf-8")
    network_env_path.write_text("TZ=UTC\n", encoding="utf-8")

    host_prefs = HostPreferences(
        username="testuser",
        uid=1000,
        gid=1000,
        docker_gid=999,
        architecture="x86_64",
        cpu_count=4,
        ram_mb=8192,
        install_dir=str(install_dir.resolve()),
        install_dir_total_gb=100.0,
    )

    monkeypatch.setattr(cli_module, "_require_init_or_exit", lambda: host_prefs)
    monkeypatch.setattr(
        cli_module,
        "_load_cached_projects",
        lambda cache_dir, check_remote_change=False: [_project_item()],
    )

    runtime_mock = MagicMock()
    monkeypatch.setattr(cli_module, "validate_compose_config", MagicMock())
    monkeypatch.setattr(cli_module, "remove_project_stack", runtime_mock)
    result = runner.invoke(cli_module.app, ["remove", "test"])

    assert result.exit_code == 0
    runtime_mock.assert_called_once_with(
        compose_path,
        "test-project",
        [env_path, host_env_path, network_env_path],
    )
    assert not project_dir.exists()
