name: ${STACK_HT_HATSH:-hat}
services:
  hat:
    image: ${DOCKER_IMAGE_HT_HATSH:-shdv/hat.s}
    container_name: ${CONTAINER_NAME_HT_HATSH:-hat}
    hostname: ${HOST_NAME_HT_HATSH:-hat}
    restart: ${RESTART_POLICY_HT_HATSH:-unless-stopped}
    networks:
      traefiknet:
        ipv4_address: ${IP_HT_HATSH:-172.16.0.15}
    deploy:
      resources:
        limits:
          cpus: ${CPU_MAX_HT_HATSH}
          memory: ${RAM_MAX_HT_HATSH}
        reservations:
          cpus: ${CPU_MIN_HT_HATSH:-0.05}
          memory: ${RAM_MIN_HT_HATSH:-6M}
    env_file:
      - .env
      - ../00.env/host.env
      - ../00.env/network.env
    # Uncomment this if not running traefik or other reverse proxy and want to access gatus directly via http://<IP_PUBLIC>:3009 or http://<IP_TAILSCALE>:3009
    # You do not need to change the external port, it is designed to work nicely with other containers.
    # ports:
    #   - ${IP_TAILSCALE}:${PORT_HT_HATSH_EXTERNAL:-3009}:${PORT_HT_HATSH_INTERNAL:-80}
    # OR if you don't want to bind to a specific IP, you can use:
    # ${PORT_HT_HATSH_EXTERNAL:-3009}:${PORT_HT_HATSH_INTERNAL:-80}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME_HT_HATSH:-hat}.entrypoints=http"
      - "traefik.http.routers.${APP_NAME_HT_HATSH:-hat}.rule=Host(`${APP_NAME_HT_HATSH:-hat}.${HOST_NAME}.${DOMAIN}`)"
      - "traefik.http.middlewares.${APP_NAME_HT_HATSH:-hat}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${APP_NAME_HT_HATSH:-hat}.middlewares=${APP_NAME_HT_HATSH:-hat}-https-redirect"
      - "traefik.http.routers.${APP_NAME_HT_HATSH:-hat}-secure.entrypoints=https"
      - "traefik.http.routers.${APP_NAME_HT_HATSH:-hat}-secure.rule=Host(`${APP_NAME_HT_HATSH:-hat}.${HOST_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME_HT_HATSH:-hat}-secure.tls=true"
      - "traefik.http.routers.${APP_NAME_HT_HATSH:-hat}-secure.service=${APP_NAME_HT_HATSH:-hat}"
      - "traefik.http.services.${APP_NAME_HT_HATSH:-hat}.loadbalancer.server.port=${PORT_HT_HATSH_INTERNAL:-80}"
      - "traefik.docker.network=traefiknet"

networks:
  traefiknet:
    name: ${DOCKER_NETWORK:-traefiknet}
    external: true
